# name: Build

# on:
#   push:
#     tags: "*"

# env:
#   CARGO_TERM_COLOR: always

# permissions:
#   contents: write

# jobs:
#   binaries:
#     runs-on: windows-latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Install Nodejs
#       uses: actions/setup-node@v4
#       with:
#         node-version-file: '.nvmrc'
#     - name: Install Rust
#       uses: actions-rust-lang/setup-rust-toolchain@v1
#       with:
#         cache: false
#     - name: Build web
#       shell: bash
#       run: npm install && npm run build && mv dist ui
#     - name: Build api
#       run: cd src-api && cargo build --verbose --release
#       env:
#         RUST_BACKTRACE: 1
#     - name: Archive
#       shell: bash
#       run: |
#         mkdir wayfinder-${{ github.ref_name }}-windows-x86_64
#         cp -r LICENSE README.md ui src-api/target/release/wayfinder.exe src-api/script/start.bat wayfinder-${{ github.ref_name }}-windows-x86_64/
#         7z a wayfinder-${{ github.ref_name }}-windows-x86_64.zip wayfinder-${{ github.ref_name }}-windows-x86_64
#     - name: Release
#       uses: softprops/action-gh-release@v2
#       with:
#         files: wayfinder-${{ github.ref_name }}-windows-x86_64.zip

#  docker:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          platforms: linux/amd64
#          push: true
#          tags: |
#            npcdw/wayfinder:${{ github.ref_name }}
#            npcdw/wayfinder:latest